services:
  ftp_server:
    build:
      context: ./ftp_server
    container_name: ftp_server
    networks:
      - inquisitor-net
    ports:
      - "21:21"
      - "20:20"

  ftp_client:
    build:
      context: ./ftp_client
    container_name: ftp_client
    networks:
      - inquisitor-net
    depends_on:
      - ftp_server

  inquisitor:
    build:
      context: ./inquisitor
    container_name: inquisitor
    networks:
      - inquisitor-net
    cap_add:
      - NET_RAW
    depends_on:
      - ftp_server
      - ftp_client

networks:
  inquisitor-net:
    driver: bridge