services:
  ftp_server:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp_server
    environment:
      - FTP_USER_NAME=anonymous
      - FTP_USER_PASS=anonymous
      - FTP_USER_HOME=/home/ftpusers/anonymous
      - FTP_MAX_CLIENTS=10
      - FTP_MAX_PER_IP=5
      - ADDED_FLAGS=--create-home
    ports:
      - "2121:21"
      - "21100-21110:21100-21110"
    networks:
      - inquisitor-net

  ftp_client:
    image: alpine:latest
    container_name: ftp_client
    networks:
      - inquisitor-net
    tty: true
    command: tail -f /dev/null

  inquisitor:
    build:
      context: ./inquisitor
    container_name: inquisitor
    networks:
      - inquisitor-net
    sysctls:
      - net.ipv4.ip_forward=0
    cap_add:
      - NET_RAW
    depends_on:
      - ftp_server
      - ftp_client

networks:
  inquisitor-net:
    driver: bridge
    name: inquisitor-net